# Generated by Django 4.0.3 on 2022-04-10 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('j_id', models.AutoField(primary_key=True, serialize=False)),
                ('JobName', models.CharField(max_length=100)),
                ('Salary', models.IntegerField()),
                ('Experience', models.IntegerField()),
                ('City', models.CharField(choices=[('Hyderabad', 'HYD'), ('Mumbai', 'MUM'), ('Chennai', 'CHN')], max_length=100)),
                ('Skills', models.TextField()),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'searches',
            },
        ),
    ]
